@echo off
cd /d "%~dp0"
echo Initializing Git...
"C:\Program Files\Git\cmd\git.exe" init
echo Adding files...
"C:\Program Files\Git\cmd\git.exe" add .
echo Committing...
"C:\Program Files\Git\cmd\git.exe" commit -m "Initial commit"
echo Branching...
"C:\Program Files\Git\cmd\git.exe" branch -M main
echo Adding Remote...
"C:\Program Files\Git\cmd\git.exe" remote add origin https://github.com/genta2223/horse-racing-dashboard.git
echo Pushing...
"C:\Program Files\Git\cmd\git.exe" push -u origin main
pause
